### ISSUE TITLE
Allow user to pass own infura id

### ISSUE THREAD

**Issue by makoto** [ensdomains/ui#5]
Currently ENS infura id is hard coded.

This causes ENS app to raise error when someone tries to deploy ENS manager to non whitelisted URL

```
Error: Returned error: rejected due to project ID settings
    at Object.ErrorResponse (errors.js:29)
    at index.js:125
```

**Comment by jefflau** [comment]
@makoto With the ethers branch merged, we shouldn't need this as I've gotten rid of the read providers as ethers seems to work without it. The read only provider uses ethers default provider. We could add infura as a back up as well, but don't really see the need right now. Can you check if this works?

**Comment by jefflau** [comment]
Closing

**Comment by itsencrypted** [comment]
Same error for me today... Project ID settings, I'm whitelisted and checked the credentials...
Can you shed a light?
“rejected due to project ID settings”.
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: RPCError: got code -32002 with msg "rejected due to project ID settings".
#0      JsonRPC.call (package:web3dart/json_rpc.dart:49:7)
<asynchronous suspension>
#1      Web3Client._makeRPCCall (package:web3dart/src/core/client.dart:58:35)
#2      Web3Client.getBalance (package:web3dart/src/core/client.dart:192:12)


Tks...Juliana, Telegram @itsencrypted

**Comment by sebastianpapuc** [comment]
![20201129_034431](https://user-images.githubusercontent.com/61084437/100530197-8ac85500-31f7-11eb-8145-67e0e0b792f3.jpg)

**Comment by sebastianpapuc** [comment]
If anyone can hellp mw i oferr 2000usd please i cant send any founds email me to seby50cent20@yahoo.com

**Comment by mato080** [comment]
Hello @sebastianpapuc,

This means that you have configured settings for your project in the Security section of the dashboard that is preventing your request from being served. You can read more about the settings here, https://infura.io/docs/gettingStarted/whitelisting

Brgds,
Martin

**Comment by milaabl** [comment]
> Same error for me today... Project ID settings, I'm whitelisted and checked the credentials... Can you shed a light? “rejected due to project ID settings”. [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: RPCError: got code -32002 with msg "rejected due to project ID settings". #0 JsonRPC.call (package:web3dart/json_rpc.dart:49:7) #1 Web3Client._makeRPCCall (package:web3dart/src/core/client.dart:58:35) #2 Web3Client.getBalance (package:web3dart/src/core/client.dart:192:12)
> 
> Tks...Juliana, Telegram @itsencrypted

@itsencrypted, Juliana, have you managed to figure that out? Wondering, because we've been having the same issue.
